services:
  - type: web
    name: rust-api
    env: docker
    buildCommand: "cargo build --release"
    startCommand: "./target/release/Goodwill_Web_Scrapper"
    plan: free
    regions:
      - oregon
